server:
  port: 8080
  servlet:
    context-path: /transport


spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/TripOrder"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



